apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e-pipeline
spec:
  selector:
    matchLabels:
      app: e2e-pipeline
  replicas: 2
  template:
    metadata:
      labels:
        app: e2e-pipeline
    spec:
      containers:
        - name: e2e-pipeline
          image: mohumadkhald/e2e-pipeline-ci_cd:1.0.0-35
          ports:
            - containerPort: 8080
