apiVersion: v1
kind: Service
metadata:
  name: e2e-pipeline-service
spec:
  selector:
    app: e2e-pipeline
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30005


